name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Pack
      run: dotnet pack --configuration Release --version-suffix "ci-${{github.sha}}" --output ${{env.DOTNET_ROOT}}/nupkgs
      working-directory: src
    - name: Push
      run: dotnet nuget push '*.nupkg' --api-key 81616cf637a33104edb25b50f714932ed6ce2fc0 --source "https://nuget.pkg.github.com/unified-dev/index.json"
      working-directory: ${{env.DOTNET_ROOT}}/nupkgs
