name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Run MinVer
      id: version
      uses: thefringeninja/action-minver@2.0.0-preview1
      with:
        auto-increment: patch     #Valid values are major, minor, or patch (default)
        default-pre-release-phase: alpha
        
    - name: Pack
      run: dotnet pack --configuration Release -p:PackageVersion=${{steps.version.outputs.version}} --output ${{env.DOTNET_ROOT}}/nupkgs
      working-directory: src
      
    - name: Push
      run: dotnet nuget push '*.nupkg' --api-key 81616cf637a33104edb25b50f714932ed6ce2fc0 --source "https://nuget.pkg.github.com/unified-dev/index.json"
      working-directory: ${{env.DOTNET_ROOT}}/nupkgs





